### ISSUE TITLE
time domain loss and CUDA

### ISSUE THREAD

**Issue by listener17** [rishikksh20/TFGAN#10]
If I run:
```
loss2 = TimeDomainLoss_v2()
a = torch.randn(32, 1, 16384).to(device='cuda')
b = torch.randn(32, 1, 16384).to(device='cuda')
final2 = loss2(a, b)
```

I get this error:
```

Traceback (most recent call last):
  File "c:\git\melganMono\melgan\models\timeloss.py", line 111, in <module>
    final2 = loss2(a, b)
  File "C:\Users\listener17\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "c:\git\melganMono\melgan\models\timeloss.py", line 90, in forward
    y_energy = F.conv1d(y**2, getattr(self, f'filters_{i}'), stride=self.strides[i])
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
```

**Comment by rishikksh20** [comment]
@listener17 yes because time domain loss is working on CPU only, actually I don't write time domain loss code. I will look out the code and make it work for both cpu and gpu.

**Comment by listener17** [comment]
@rishikksh20 Thanks. 
OK, I made a change, and I can run on GPU now.
